name: Build
on: [ push ]
jobs:
  Java:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        distribution:
          - temurin
          - microsoft
          - corretto
          - oracle
          - graalvm
          - jetbrains
        version: [21]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: ${{ matrix.distribution }}
          java-version: ${{ matrix.version }}
          cache: gradle

      - name: Test
        run: make test
