name: Build
on: [ push ]
jobs:
  Java:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [11, 17, 21, 25]
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: temurin
          java-version: ${{ matrix.version }}
          cache: gradle

      - name: Test
        run: make test
